language: python
before_script:
  - "curl -s http://arduino.googlecode.com/files/arduino-${ARDUINO_IDE_VERSION}-linux64.tgz | sudo tar xz -C /opt"
  - "git clone -q https://github.com/errordeveloper/hwci-scripts ../hwci-scripts && ../hwci-scripts/bin/setup.sh"
  - "git clone -q https://github.com/amcewen/HttpClient ../HttpClient"
script:
  - "for e in `ls -d examples/*/` \
    ;do env \
        USER_LIB_PATH=$PWD/../ \
        ARDUINO_DIR=/opt/arduino-${ARDUINO_IDE_VERSION} \
        ../hwci-scripts/bin/arduino_make.sh -C $e \
      && echo pass:$e >> results \
      || echo fail:$e >> results \
    ;done"
  - "cat results"
  - "cut -d: -f1 results | sort | uniq -c"
  - "test `grep -c fail results` -eq 0"

env:
  - ARDUINO_IDE_VERSION='1.0.2'
  - ARDUINO_IDE_VERSION='1.0.3'
